var url="https://jsonplaceholder.typicode.com/comments";


// Get Method
/*

async function getArtical()
{
    console.log("mydata")
    let data=await fetch(url);
    console.log(data)
    
    let mydata=data.json();
    return new Promise((resolve,reject)=>{
        resolve(mydata)
    })

}



async function getList()
{
    console.log("mylist");
    let newdata=await getArtical();
    console.log(newdata[0].name)
}
getList();

*/
//Post Method

